import tokens

import random
from flask import Flask, request
from pymessenger.bot import Bot

app = Flask(__name__)
# token generated by facebook that identifies our app and our permissions
ACCESS_TOKEN = tokens.ACCESS_TOKEN
# token generated by us that is used by facebook to verify 
# that we only accept and respond to requests sent from Messenger
VERIFY_TOKEN = tokens.VERIFY_TOKEN
bot = Bot(ACCESS_TOKEN)

@app.route('/', methods=['GET', 'POST'])
def receive_message():
    # GET requests will be used when Facebook needs to check our verify token
    # which confirms the bot only responds to requests sent from Messenger
    if request.method == 'GET':
        token_sent = request.args.get("hub.verify_token")
        return verify_fb_token(token_sent)
    # POST requests will be used to send messages back to the user
    else:
        output = request.get_json()
        for event in output['entry']:
            messaging = event['messaging']
            for message in messaging:
                if message.get('message'):
                    # Facebook Messenger ID tells us where to send response
                    recipient_id = message['sender']['id']
                    if message['message'].get('text'):
                        response_sent_text = get_message()
                        send_message(recipient_id, response_sent_text)
                    # If user sends a GIF, photo, video, or any non text item
                    if message['message'].get('attachments'):
                        response_sent_nontext = get_message()
                        send_message(recipient_id, response_sent_nontext)
    return "Message Processed"

def verify_fb_token(token_sent):
    # match verify token sent by Facebook with the verify token we sent
    # if they match, allow the request
    if token_sent == VERIFY_TOKEN:
        return request.args.get("hub.challenge")
    return "Invalid verification token"

def get_message():
    # array of random responses
    sample_responses = ["Rob to the rescue, what seems to be the problem today?", "Rob to the rescue, what can I help you with?"]
    return random.choice(sample_responses)

def send_message(recipient_id, response):
    # uses method from the pymessenger API to handle to POST request
    bot.send_text_message(recipient_id, response)
    return "Success"

if __name__ == '__main__':
    app.run()
